(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,92,131,86],[730,0,193,90],[925,62,82,41],[0,0,728,90],[250,92,117,50],[133,92,115,54],[925,0,71,60]]}
];


// symbols:



(lib.leaderboardbrusselsprouts = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.leaderboardcinnamonbuns = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.leaderboardcranberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.leaderboardholidaymainstable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.leaderboardorange = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.leaderboardpotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.leaderboardstuffinguse = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.youtakethecredit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgFAGQgCgDAAgDQAAgCACgDQADgCACAAQADAAACACQADADAAACQAAADgDADQgCACgDAAQgCAAgDgCg");
	this.shape.setTransform(67.6,3.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AABApIgCAAIgDgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAg7QAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAIgDgBIgHAAIgGAAIgDAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgBgEIAAgCIAAgDIABgCIADgBIA4AAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABIAAADIAAADIAAADIgBACIgDABIgQAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIABA7IgBADIgDABg");
	this.shape_1.setTransform(62.5,-0.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgCAqQgDAAgCgCIAAhPIACgCIADAAIACAAIADAAQADAAACADIAABNIgCACIgDABIgDAAg");
	this.shape_2.setTransform(57.3,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgiApIgDgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhJQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAgBIADgBIAeAAIAIABIAIACQAIADAGAFQAGAGAEAHIACAIIABAIQAAAJgDAIIgEAHIgGAGIgGAEIgIAEQgIADgIAAgAgWgYIgBADIAAAsQAAABAAAAQAAAAABABQAAAAAAAAQAAABABAAIADABIAOAAQAFAAAFgCQAGgCAEgEQAEgDACgFQACgFAAgGQAAgFgCgFQgCgFgEgDQgEgEgGgCQgFgBgFAAIgOAAIgEABg");
	this.shape_3.setTransform(51.2,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgbApIgDgBIgBgCIAAhLQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBAAAAIADgBIA4AAIACACIABACIAAADIAAACIgBADIgCADIgqAAIgCABIAAACIAAALIAAADIADABIAbAAIACABIABADIAAADIAAACQAAADgEABIgaAAIgDACIAAACIAAANIAAADIADABIApAAQADABAAADIAAADIAAADIgBADIgCABg");
	this.shape_4.setTransform(42.6,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AAVAqIgCgBIgCgBIgBgBIgOgWIgCgCIgEgBIgKAAIgCABQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAIABAUQAAAAgBABQAAAAAAAAQAAAAAAABQgBAAAAAAIgDABIgDABIgCAAIgFgBQAAgBAAAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAhLIABgCIADAAIAiAAQAGAAAGACQAEABAFAEQAEADACAFQACAGAAAGQAAAHgDAEIgFAHIgGADQgBABAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAACIADAEIAFAHIADAHIACAEIgBADIgCABIgDABIgDABgAgQgaQgBABAAAAQAAAAgBABQAAAAAAABQAAAAAAABIAAASQAAABAAAAQAAABAAAAQABABAAAAQAAAAABAAIADABIAQAAIAHAAIAEgCIAEgFIABgGQAAgHgFgDIgEgDIgHgBIgQAAIgDABg");
	this.shape_5.setTransform(34.4,-0.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgDAqIgIgCIgHgFIgHgEIgFgGIgEgIQgEgIAAgJQAAgIAEgIIAEgHIAFgGQAGgGAIgDIAIgCIAIgCIAJACIAJADIAJAEIAGAGIABACQAAABAAABQAAAAAAABQgBAAAAAAQAAABAAAAIgEACIgDACIgCABIgDgCIgFgDIgHgFQgDgBgGAAQgFAAgFACQgFADgEADQgEAEgCAFQgCAFAAAFQAAAGACAFIAGAJQAEAEAFACQAFACAFAAQAGAAAGgCQAFgDAFgEIACgBIADABIADACIADADIABACIgBABQgCAFgFACIgIAFIgJADIgJABIgIgBg");
	this.shape_6.setTransform(25.5,-0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgbApIgCgBIgCgCIAAhLQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIACgBIA5AAIACACIAAACIAAADIAAACIAAADIgCADIgqAAIgCABIgCACIAAALQAAABABAAQAAABAAAAQAAAAAAAAQAAABABAAIACABIAbAAIABABIABADIAAADIAAACQAAADgCABIgaAAIgDACIgCACIAAANIACADIACABIAqAAQACABAAADIAAADIAAADIgBADIgCABg");
	this.shape_7.setTransform(14.2,-0.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AAWApIgDgCIAAgcQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAIgDgBIgaAAQgBAAAAAAQgBAAAAAAQgBABAAAAQAAAAgBABQAAAAAAAAQgBABAAAAQAAABAAAAQAAAAAAABIAAAcQAAAAAAABQAAAAgBAAQAAABAAAAQAAAAgBAAIgDABIgDAAIgDAAIgDgBIgCgCIAAhOIACgBIADgBIADAAIADAAQADAAACADIAAAaIABADQAAAAAAABQABAAAAAAQAAAAABAAQAAABAAAAIAcAAIADgCQABAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAgBIAAgaQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIAFAAIADAAIADADIAABNQgBABAAAAQAAABgBAAQAAAAgBAAQAAAAgBAAIgFABg");
	this.shape_8.setTransform(5.5,-0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AABApIgCAAIgDgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAg7QAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAIgDgBIgHAAIgGAAIgDAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgBgEIAAgCIAAgDIABgCIADgBIA4AAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAABABIAAADIAAADIAAADIgBACIgDABIgQAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIABA7IgBADIgDABg");
	this.shape_9.setTransform(-2.4,-0.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgbApIgCgBIgCgCIAAhLQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIACgBIA5AAIACACIAAACIAAADIAAACIAAADIgCADIgqAAIgCABIgCACIAAALQAAABABAAQAAABAAAAQAAAAAAAAQAAABABAAIACABIAbAAIABABIABADIAAADIAAACQAAADgCABIgaAAIgDACIgCACIAAANIACADIACABIAqAAQACABAAADIAAADIAAADIgBADIgCABg");
	this.shape_10.setTransform(-12.8,-0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AATAqIgDgCIgUgfIgDgCIgDAAIgEABQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIAAAaIgBADIgCABIgEAAIgDAAQgFAAAAgEIAAhMIADgCIACgBIACAAIAEAAQADAAABADIAAAaQAAAAABABQAAAAAAABQAAAAAAAAQABABAAAAIAEABQAAAAAAAAQABgBAAAAQABAAAAAAQABgBAAAAIAXgcIABgBIACAAIACABIAEABIACADIABACIgBACIgUAXIAAACIgBACIAAACIABACIAaAjIAAABIABABIgCACIgDACIgDABIgCABg");
	this.shape_11.setTransform(-20.6,-0.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AAeApIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBgBAAIgEgLIgCgBIgCgCIgbAAIgBABIgBABIgBABIgBAAIgEALIgCABIgCABIgDABIgCAAIgCAAIgCAAIgDgBIgBgCIAihMQAAAAAAgBQAAAAABAAQAAAAAAgBQABAAAAAAIACgBIADABQABAAAAAAQABABAAAAQABAAAAAAQAAABAAAAIAhBMIAAAAIgBACIgDABIgDAAgAgBgLIgBACIgBAEIgDAFIgBADIgCAEIAAACIAAACIACAAIAPAAIACAAIABgCIgCgEIgCgFIgDgHIgCgFIgCAAIAAAAg");
	this.shape_12.setTransform(-29,-0.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AABApIgCAAIgDgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAg7QAAgBAAAAQAAgBgBAAQAAAAAAgBQAAAAgBAAIgDgBIgHAAIgGAAIgDAAQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAAAgBIgBgEIAAgCIAAgDIABgCIADgBIA4AAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABIAAADIAAADIAAADIgBACIgDABIgQAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIABA7IgBADIgDABg");
	this.shape_13.setTransform(-36.3,-0.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgNAnQgHgCgFgFQgFgEgCgHIgDgHIAAgGIAAgXIAAgWIABgDIADgBIADAAIACAAIAEABQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAAAIAAAqQAAAFABAEIAEAIIAHAFQAEACAEAAQAFAAAEgCQAEgCADgDIAEgIQABgEAAgFIAAgpQAAgBAAAAQAAgBABAAQAAgBAAAAQAAAAABgBIAEgBIADAAIADABIACABIABADIAAAtIgBAGIgCAHQgDAHgEAEQgFAFgHACQgGADgIAAQgHAAgGgDg");
	this.shape_14.setTransform(-47.7,-0.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgIAqIgIgCIgIgFIgGgEQgGgHgEgHIgCgIIgBgJIABgIIACgIQAEgHAGgGIAGgFIAIgEIAIgCIAIgCIAJACIAIACQAIADAGAGQAGAGADAHQAEAIAAAIIgBAJIgDAIQgDAHgGAHQgGAFgIAEIgIACIgJABIgIgBgAgKgZIgJAGQgEAEgCAFQgCAFAAAFQAAAGACAFQACAGAEADQAEAEAFACQAFACAFAAQAFAAAFgCQAFgCAEgEQAEgDADgGQACgFAAgGQAAgFgCgFQgDgFgEgEIgJgGQgFgCgFAAQgFAAgFACg");
	this.shape_15.setTransform(-57.1,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgBArIgBAAIgCgBIgCgBIAAgBIAAgdIgBgFIgCgEIgYgkIAAgBIABgCIACgCIAEgCIADAAIACAAIACACIAQAbIACABIABABIACgBIABgBIARgbIACgCIADgBIACABIADABIADACIABACIAAABIgBABIgXAkIgCAFIAAACIgBABIAAAdQAAABAAABQgBAAAAABQgBAAAAAAQgBABAAAAg");
	this.shape_16.setTransform(-65.6,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.youtakethecredit, new cjs.Rectangle(-71.4,-7.9,143,16), null);


(lib.wellmakethefeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgNAOQgGgGAAgIQAAgHAGgGQAGgGAHAAQAIAAAGAGQAGAGAAAHQAAAIgGAGQgGAGgIAAQgHAAgGgGg");
	this.shape.setTransform(121.5,7.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgGBNQgGgCgFgFQgEgEgCgHQgCgHAAgTIAAhDIgMAAIgEgBIgBgEIAAgCQAAgFANgLIAGgFIAFgEQANgLAFAAIADABIABACIAAAZIAcAAQABAAABAAQABAAAAAAQABAAAAAAQABAAAAABIABAEIAAAEIgBAEQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAgBAAIgaAAIgCABIAAADIAAA+QAAARACADQAEAFAHAAQAEAAAGgDIAJgCQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAGgLAHQgLAGgNAAQgHAAgGgBg");
	this.shape_1.setTransform(113.6,1.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgJBCIgNgCIgEACIgEABIgDgBIgCgCQgEgDgEgKQgEgLAAgJQAAgEACgDQADgCADAAQAGAAAGAKIAFAHQADAFAHADQAGADAHAAQAIAAAFgEQAFgEAAgHQAAgLgUgKIgHgEQgUgKgHgHQgHgIAAgMQAAgRALgKQAMgLASAAIAIABIAJABIAGgCIAEgBQAGAAAGAKQAGAKAAALQAAAFgCACQgCADgDAAQgDAAgDgDQgDgCgEgGQgFgIgFgDQgFgDgHAAQgGAAgFAEQgEAEAAAHQAAAGAEAEQAFAFAPAHIABABQAkARAAAUQAAASgOAMQgNAMgVAAg");
	this.shape_2.setTransform(103.5,2.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAWA8IgGgHIgFADQgQALgQAAQgSAAgLgMQgMgKAAgSQAAgUAPgKQAPgMAaAAQAGAAADACQADACAAAEQAAAHgIAAQgMAAgIAGQgIAHAAAKQABAKAGAHQAHAFALAAQALABAGgGQAFgFAAgOIAAgvQAAgLgFgHQgEgFgJAAQgGAAgGACQgFADgFAGIgCADQgIAKgJAAQgFAAgCgDQgEgDAAgGQAAgMAPgIQAPgJAXABQANAAAKADQALAEAFAHQAEAFACAIQABAHAAATIAAAnIABAMQABADADAAIAEACQAIACAAAFQAAAFgIAFQgJAFgMABQgFgBgHgGg");
	this.shape_3.setTransform(91.5,3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgpAwQgSgTAAgbQAAgdATgTQASgTAcAAQAZAAAOAOQAPAOAAAXQAAAIgDADQgCACgJAAIgwAAQgFAAgCgCQgCgCAAgDQAAgEACgBQACgCAEAAIAaAAIAHgBQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgMgIgJQgIgIgMAAQgOAAgIANQgHANAAATQAAATAKAPQAKAOAQAAQAJAAAGgCQAHgCAGgEIAFgEQAGgFAEAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAADgDAFIgJAIQgLAJgKAEQgKAEgMAAQgbAAgSgSg");
	this.shape_4.setTransform(77.8,2.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AhABbQgHgCAAgGQAAgFAHgCQAHgDABgCQACgDABgTIABgxIgBguQgCgTgBgDQgBgBgHgEQgHgCAAgGQAAgEAGgCQAGgCAWgBIBNAAIAMgBIAHgBIADABIACACQADAEACAJQADAJAAAGQAAAGgCADQgCADgEAAQgFAAgFgJIgEgGQgCgDgGgCQgGgDgIAAIgSAAQgLAAgGACQgHABgCADQgCACgBAJIgBAYIAAAKQAAAHABABQAAAAABABQAAAAABAAQAAAAABAAQABAAABAAIAUAAQAKAAAEgCQAEgDABgIIAAgDQACgNAHAAQAGAAACAHQACAHAAAYQAAAYgCAHQgCAGgGAAQgHAAgCgNIAAgCQgBgIgEgDQgEgDgKAAIgUAAQgEAAgBACQgBACAAAIIAAALIABAjQABAIACABIAGADQAHADAAAFQAAAGgHACQgHACgTAAQgVAAgHgCg");
	this.shape_5.setTransform(63.6,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgpAwQgSgTAAgbQAAgdATgTQASgTAcAAQAZAAAOAOQAPAOAAAXQAAAIgDADQgCACgJAAIgwAAQgFAAgCgCQgCgCAAgDQAAgEACgBQACgCAEAAIAaAAIAHgBQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgMgIgJQgIgIgMAAQgOAAgIANQgHANAAATQAAATAKAPQAKAOAQAAQAJAAAGgCQAHgCAGgEIAFgEQAGgFAEAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAADgDAFIgJAIQgLAJgKAEQgKAEgMAAQgbAAgSgSg");
	this.shape_6.setTransform(42.1,2.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AASBcQgHgDAAgEQAAgFAHgDIAFgCQADgBABgGIABgTQAAgpgFgJQgFgKgNAAQgGAAgHAEQgGAEgDAGQgDAFgBAKIgBAjQAAANABAEQABAEACABIAGACQAGADAAAFQAAAEgGADQgHABgQAAQgUAAgGgCQgHgCABgFQgBgEAHgDIAEgBQADgCABgFQABgGAAgOIAAgUIAAgUIAAg5QgBgOgCgCQgCgCgHgCQgHgCgBgFQAAgDADgDQAEgCALgEIANgEIAMgBQADAAACACQADADAAAFIgBAGIgBAyIAAAHIABADIACABIACgDIAFgFQAGgGAHgEQAHgDAIAAQAVAAALAOQALAPAAAbIAAAMIAAAXIAAAHIABAJQABADADACIAEABQAFACAAAFQABAFgGACQgGACgUAAQgRAAgGgBg");
	this.shape_7.setTransform(27.6,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgGBNQgHgCgEgFQgEgEgCgHQgCgHAAgTIAAhDIgMAAIgEgBIAAgEIAAgCQgBgFANgLIAGgFIAEgEQAOgLAFAAIADABIABACIAAAZIAcAAQABAAABAAQABAAAAAAQABAAAAAAQABAAAAABIABAEIAAAEIgBAEQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAgBAAIgaAAIgCABIAAADIAAA+QAAARACADQAEAFAGAAQAFAAAGgDIAJgCQABAAAAABQABAAAAAAQABAAAAAAQABABAAAAQABABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAGgLAHQgLAGgNAAQgHAAgGgBg");
	this.shape_8.setTransform(15.9,1.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgpAwQgSgTAAgbQAAgdATgTQASgTAcAAQAZAAAOAOQAPAOAAAXQAAAIgDADQgCACgJAAIgwAAQgFAAgCgCQgCgCAAgDQAAgEACgBQACgCAEAAIAaAAIAHgBQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgMgIgJQgIgIgMAAQgOAAgIANQgHANAAATQAAATAKAPQAKAOAQAAQAJAAAGgCQAHgCAGgEIAFgEQAGgFAEAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAADgDAFIgJAIQgLAJgKAEQgKAEgMAAQgbAAgSgSg");
	this.shape_9.setTransform(-2.5,2.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AApBdIgFgBQgGgCgMgPIgFgHIgCgDQgfgogCAAIgCABIAAAGIAAAFIAAAbQABAHACADIAHADQAGADAAAFQAAAEgGADQgHABgQAAQgUAAgGgCQgGgCAAgFQAAgFAGgCIAEgBQADgCABgGQACgHAAgOIAAgQIgBgUIAAgPIAAgvQgBgMgCgCQgBgBgGgCIgEgBIgFgDIgBgDQAAgDACgCQADgDAJgDIARgEIANgCQAEAAABACQACACAAAGIgBAZIAAAhIAAAfIAAAGIACACIAFgDIAKgIIALgLQAEgEAAgCQAAgBgFgDQgEgCAAgEQAAgGAGgCQAGgCASAAQAMAAAGACQAGACAAAFQAAAGgJADQgKACgEACQgEADgLAKIgCACIgFAFIgBACQAAADALAOIACACIAVAbIAOAOIAMAFQAIACAAAFQAAAGgGACQgGACgOAAg");
	this.shape_10.setTransform(-15.8,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AAXA8IgHgHIgGADQgPALgPAAQgTAAgMgMQgLgKAAgSQAAgUAPgKQAPgMAaAAQAGAAAEACQADACAAAEQAAAHgJAAQgMAAgIAGQgHAHAAAKQAAAKAGAHQAGAFAMAAQAMABAFgGQAFgFAAgOIAAgvQAAgLgFgHQgEgFgJAAQgGAAgFACQgGADgEAGIgEADQgHAKgJAAQgFAAgCgDQgEgDAAgGQAAgMAPgIQAPgJAXABQANAAALADQAKAEAFAHQAEAFABAIQACAHAAATIAAAnIABAMQABADADAAIAEACQAIACAAAFQAAAFgJAFQgIAFgMABQgFgBgGgGg");
	this.shape_11.setTransform(-30,3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AAvBaQgGgCAAgGQAAgFAIgDIAFgDQADgCAAgFQABgGAAgRIAAgHIAAg1IAAggIgQAqQgmBhgIAAQgEAAgHgOQgIgNgRgpIgchAIgBAyIgBAiIABAYQABAGACABIAFADQAJADgBAFQAAAFgGADQgGACgQAAQgOAAgGgCQgGgDgBgFQAAgFAIgDQAGgDABgDQABgGACghQACgfAAgpIAAgEIgBgRQgBgFgCgCIgHgCQgIgDAAgGQAAgFAGgCQAGgCASAAIATABIAEABQADACAJAWIAHASIAEAJQAfBMABAAQADAAAMgbQALgbAQgsIACgIQAFgOADgEQADgDAFgBIARgBQARAAAFACQAHACgBAFQAAAGgHACIgDACQgEACgCAFQgBAFAAATIABBIIADAlQABADAFACIADABIAFADQAAABABAAQAAABAAAAQAAABAAABQAAAAAAABQABAGgIACQgGACgWAAQgSAAgIgCg");
	this.shape_12.setTransform(-48.4,0.1);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgVBbQgGgCAAgFQAAgEAFgDIAHgDQACgCABgIIABgZIAAgUIgBgXIAAgKQAAgggBgJQgBgJgCgCIgIgCQgIgDAAgEQAAgDACgCQADgDAJgDIARgEIAMgCQAEAAABACQACACAAAGIAAAKQgCAtAAAuIABArQABAJACADIAHADQAGADAAAFQAAAEgGADQgHABgQAAQgTAAgGgCg");
	this.shape_13.setTransform(-70.7,0);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgVBbQgGgCAAgFQAAgEAFgDIAHgDQACgCABgIIABgZIAAgUIgBgXIAAgKQAAgggBgJQgBgJgCgCIgIgCQgIgDAAgEQAAgDACgCQADgDAJgDIARgEIAMgCQAEAAABACQACACAAAGIAAAKQgCAtAAAuIABArQABAJACADIAHADQAGADAAAFQAAAEgGADQgHABgQAAQgTAAgGgCg");
	this.shape_14.setTransform(-77.8,0);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgBAlIgJg3IAAgCIAAgDQAAgGACgDQADgEAFAAQAFAAAEAEQACADAAAGIAAADIAAACIgJA3g");
	this.shape_15.setTransform(-83.3,-4.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgpAwQgSgTAAgbQAAgdATgTQASgTAcAAQAZAAAOAOQAPAOAAAXQAAAIgDADQgCACgJAAIgwAAQgFAAgCgCQgCgCAAgDQAAgEACgBQACgCAEAAIAaAAIAHgBQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBQAAgMgIgJQgIgIgMAAQgOAAgIANQgHANAAATQAAATAKAPQAKAOAQAAQAJAAAGgCQAHgCAGgEIAFgEQAGgFAEAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAADgDAFIgJAIQgLAJgKAEQgKAEgMAAQgbAAgSgSg");
	this.shape_16.setTransform(-92.2,2.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E47").s().p("AARAsIgahFQgJgXgFgLQgFgLgEgDIgHgDQgHgDAAgEQAAgGAGgCQAGgCAYAAQAXAAAGACQAGACAAAGQAAAFgJADIgBABIgFACQgBACgBADQAAAFAHARIAUA3IAJAUQADAGADAAQABAAACgFIAJgSIACgGQAbg+gBgIQAAgEgBgDQgCgCgFgCIgCgCQgIgDAAgEQAAgGAGgCQAEgCAWAAQATAAAFACQAGACAAAGQAAAEgIAEIgFACQgJAGgQArIgMAaIgXA8IgFALQgIAVgFAAQgHAAgTgygAg0BTIgCgEQgPgjgahBIgLgeIgIgQQgDgFgEgCIgEgCQgIgCAAgFQAAgGAGgCQAGgCAYAAQAYAAAGACQAGACAAAGQAAAFgKADIgBAAIgFADQgBACAAADQAAAEAGAPIAVA4IAJAXQADAFADAAQABAAADgHIAGgOQADgJAHAAQAIAAAAAJIgBAIIgRAoIgEAKQgHAVgGAAQgEAAgFgLg");
	this.shape_17.setTransform(-112,0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakethefeast, new cjs.Rectangle(-127.2,-17.1,254.5,34.2), null);


(lib.wellmakethe = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgwA3QgVgVABggQgBghAWgXQAWgWAgAAQAdAAAQAQQARARAAAbQAAAJgCADQgDADgLAAIg4AAQgFAAgDgCQgCgDAAgEQAAgEACgCQADgCAFAAIAeAAIAHgBQABAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQABgPgKgJQgKgKgNAAQgRAAgJAPQgIAQAAAVQgBAWAMARQAMARASAAQALAAAIgCQAHgDAHgFIAGgEQAHgGAEAAQADAAADACQABACABADQAAAEgEAFQgEAFgGAFQgNALgMAEQgMAFgOAAQgeAAgWgWg");
	this.shape.setTransform(93.1,3.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AAVBqQgIgDAAgFQAAgGAIgDIAFgCQAEgCABgGIABgWQAAgwgGgKQgFgMgQAAQgHAAgHAEQgHAFgEAHQgDAGgCAMIgBAoIABAUQABAEAEACIAFACQAIADAAAGQAAAFgIADQgHACgTAAQgXAAgHgCQgHgDAAgGQAAgFAHgDIAEgBQAEgDACgGQABgGAAgQIAAgYIAAgXIgBhCQgBgQgCgDQgCgCgIgCQgJgDAAgFQAAgEAEgDQADgDANgFIAPgEIAOgBQAFAAACADQACACAAAHIgBAGIgBA7IAAAHIABAEIACABIADgDIAFgGQAIgIAIgDQAIgEAJAAQAZAAANARQAMAQAAAgIAAAOIAAAaIAAAJQAAAHACADQABAEADACIAEABQAHADAAAFQAAAGgHADQgHACgXAAQgTAAgHgCg");
	this.shape_1.setTransform(76.2,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgHBZQgIgDgFgEQgFgGgCgIQgCgHAAgXIAAhOIgOAAIgEgBIgBgEIAAgEQAAgEAPgOIAGgEIAGgGQAPgNAGAAIADACQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIAAAbIAhAAQAEABABABIABAFIAAAEIgBAFQgCACgDAAIgeAAIgDABIAAAEIAABIQAAATADAFQADAFAJAAQAEAAAIgCIAKgDQADAAACACQACACAAADQAAAIgMAHQgNAIgQAAQgIAAgHgCg");
	this.shape_2.setTransform(62.6,2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgvA3QgWgVAAggQAAghAXgXQAVgWAhAAQAcAAARAQQARARAAAbQAAAJgEADQgCADgLAAIg4AAQgFAAgCgCQgDgDAAgEQAAgEADgCQACgCAFAAIAeAAIAIgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQAAgPgKgJQgKgKgNAAQgRAAgJAPQgJAQAAAVQAAAWANARQALARASAAQALAAAHgCQAIgDAHgFIAFgEQAIgGAEAAQADAAACACQACACABADQgBAEgEAFQgDAFgGAFQgNALgMAEQgMAFgOAAQgeAAgVgWg");
	this.shape_3.setTransform(41.4,3.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AAwBsIgGgBQgHgDgOgSIgGgIIgCgDQgkgugDAAQAAAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAIAAAHIAAAGIABAfQAAAJADACIAIAEQAHADAAAGQAAAFgIADQgHACgTAAQgXAAgHgCQgHgDAAgGQAAgFAHgDIAEgBQAEgDACgHQABgHAAgRIAAgSIAAgXIAAgSIgBg2QgBgOgCgDQgCgBgHgCIgEgCIgGgCIgBgFQAAgDADgDQADgCAKgEIAUgFIAPgCQAFAAABACQACADAAAHIgBAcIAAAnIAAAkIAAAHQAAABABAAQAAAAAAAAQAAABABAAQAAAAAAAAIAHgEIAKgIIAOgOQAEgEAAgCQAAgCgGgDQgEgDAAgEQAAgHAHgCQAHgDAVAAQAOAAAHADQAGACAAAGQAAAHgKADQgLACgFADQgFADgNAMIgCACIgFAGIgBADQAAADAMARIACACIAZAeQALANAFAEQAEACAKADQAJADAAAGQAAAHgHACQgHADgPAAg");
	this.shape_4.setTransform(25.9,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AAaBFIgIgHIgGACQgSANgSAAQgVAAgOgNQgNgMAAgVQAAgXARgMQARgNAfAAQAHAAAEABQADADAAAGQAAAIgJAAQgPgBgJAIQgJAGAAANQAAALAIAIQAIAHANAAQANAAAHgHQAGgGAAgPIAAg4QAAgMgGgIQgGgGgJgBQgHAAgHAEQgGACgGAIIgDADQgJAMgKgBQgGAAgDgDQgDgEAAgGQAAgOARgKQARgJAbAAQAPAAAMAEQAMAFAGAHQAFAHABAJQACAIAAAVIAAAvQAAAIACAFQABADADABIAFACQAJACAAAFQAAAIgKAFQgKAGgNAAQgHAAgHgIg");
	this.shape_5.setTransform(9.4,3.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AA3BoQgIgDAAgGQAAgGAJgEIAHgDQACgCABgGQABgHAAgUIAAgIIAAg+IgBglIgSAxQgrBwgJAAQgFAAgIgPQgJgPgVgxIgghJIgBA5IgBApIABAbQABAGACACIAHADQAJADAAAHQAAAGgHACQgIADgSABQgQgBgHgDQgIgCAAgHQAAgEAIgFQAIgDABgDQACgIACglQACgmAAguIAAgEQAAgQgBgFQgBgFgDgDIgHgDQgKgDAAgGQAAgGAHgCQAGgDAWABIAVAAIAGABQACACALAaIAIAWIAFAKQAjBYACAAQAEAAANggQANgfASgzIADgJQAGgRAEgFQADgDAFgBIAVAAQATgBAHADQAHACAAAGQAAAGgJADIgEABQgEADgCAGQgBAGAAAWIABBUIADArQABADAGADIADABIAGAEQACACAAADQAAAGgIADQgIADgZAAQgWAAgIgDg");
	this.shape_6.setTransform(-12,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgYBqQgIgDAAgGQABgFAFgCIAIgEQADgDABgJIABgdIAAgXIgBgbIAAgLQAAglgBgLQgBgLgDgCIgJgDQgJgCAAgGQAAgDACgDQADgCALgEIAUgFIAOgCQAEAAACACQACADAAAHIAAALQgCA1AAA1IABAyQABAKADADIAIAEQAGADAAAGQABAFgIADQgIACgSAAQgWAAgHgCg");
	this.shape_7.setTransform(-37.7,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgYBqQgHgDAAgGQAAgFAFgCIAIgEQADgDABgJIABgdIAAgXIAAgbIAAgLQAAglgBgLQgCgLgDgCIgJgDQgKgCAAgGQAAgDADgDQAEgCAKgEIATgFIAPgCQAFAAABACQACADAAAHIAAALQgCA1AAA1IABAyQABAKACADIAJAEQAGADABAGQAAAFgIADQgIACgSAAQgWAAgHgCg");
	this.shape_8.setTransform(-46,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgCArIgKhAIAAgDIAAgDQgBgHAEgEQAEgEAFAAQAHAAADAEQADAEABAHIAAAEIgBACIgKBAg");
	this.shape_9.setTransform(-52.4,-5.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AgwA3QgUgVgBggQAAghAXgXQAVgWAhAAQAcAAARAQQARARAAAbQgBAJgDADQgCADgLAAIg4AAQgFAAgCgCQgDgDAAgEQAAgEADgCQACgCAFAAIAeAAIAIgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQAAgPgKgJQgKgKgNAAQgSAAgIAPQgJAQAAAVQAAAWANARQALARASAAQALAAAHgCQAIgDAHgFIAFgEQAIgGAEAAQADAAACACQACACAAADQAAAEgEAFQgDAFgGAFQgNALgMAEQgMAFgOAAQgfAAgVgWg");
	this.shape_10.setTransform(-62.7,3.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AAUA0IgfhRQgJgbgGgNQgGgMgFgEIgJgEQgHgCAAgGQAAgGAHgCQAHgDAcABQAbgBAGADQAHACAAAGQAAAGgLAEIgBAAQgEABgBADQgCACAAADQAAAGAHATIAZBAIAKAYQADAHACAAQADgBACgFIAKgVIADgGQAehJAAgJQAAgFgCgDQgCgDgFgCIgDgCQgJgDAAgGQAAgGAGgCQAGgDAYABQAXgBAGADQAGACAAAGQAAAGgIADIgGADQgLAHgTAzIgNAdIgcBGIgFANQgJAYgGAAQgIgBgWg4gAg8BgIgCgFQgTgogdhMIgNgjIgJgSQgEgGgEgDIgFgBQgJgDAAgGQAAgGAHgCQAHgDAcABQAcgBAGADQAHACAAAGQAAAGgLAEIgBAAQgEACgBACQgCACAAADQAAAFAGASIAZBBIALAaQADAGACAAQADAAADgIIAHgRQAEgJAIAAQAJgBAAALIgCAJIgTAuIgEALQgKAYgGABQgFgBgFgMg");
	this.shape_11.setTransform(-85.7,0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakethe, new cjs.Rectangle(-103,-19.5,206,39.1), null);


(lib.theturkey = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgQAQQgGgHAAgJQAAgJAGgGQAIgHAIAAQAJAAAHAHQAHAGAAAJQAAAJgHAHQgHAHgJAAQgIAAgIgHg");
	this.shape.setTransform(47.5,8.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhDBhQgIgGABgJQAAgHAEgGQAGgFAHAAIAGABIAFADIAEAGQAEAFADAAQAHABAIgLQAIgLAAgLQgBgOgJgWIgCgEIgXgzIgPgdQgCgFgJgEIAAAAQgEgCgDgCQgBgCAAgDQAAgHAIgCQAHgCAWgBQAVAAAHACQAIADAAAGIgBAFIgCACIgGACQgGADABADIACAKIAMAeIAMAcQADAHACAAQACAAADgHIAKgXIAKgdQAEgLAAgEQAAgEgIgFQgJgEABgEQAAgGAGgCQAHgCARAAQARAAAHACQAGADAAAGQAAAFgJACIgFACQgJAFgJAZIgFAMIgTAuQgYA9gOATQgQASgVAAQgMAAgGgGg");
	this.shape_1.setTransform(36.2,6.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgwA3QgUgVgBggQABghAVgXQAWgWAhAAQAcAAARAQQAQARAAAbQAAAJgDADQgCADgLAAIg4AAQgFAAgDgCQgCgDAAgEQAAgEACgCQADgCAFAAIAeAAIAIgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQAAgPgKgJQgKgKgNAAQgSAAgIAPQgJAQAAAVQABAWAMARQALARASAAQALAAAIgCQAHgDAHgFIAFgEQAIgGAEAAQADAAACACQACACAAADQAAAEgDAFQgEAFgGAFQgNALgMAEQgMAFgOAAQgfAAgVgWg");
	this.shape_2.setTransform(20.9,3.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AAwBsIgGgBQgHgDgOgSIgGgIIgCgDQgkgugDAAQAAAAAAAAQgBAAAAAAQAAAAAAABQgBAAAAAAIAAAHIAAAGIABAfQAAAJADACIAIAEQAHADAAAGQAAAFgIADQgHACgTAAQgXAAgHgCQgHgDAAgGQAAgFAHgDIAEgBQAEgDACgHQABgHAAgRIAAgSIAAgXIAAgSIgBg2QgBgOgCgDQgCgBgHgCIgEgCIgGgCIgBgFQAAgDADgDQADgCAKgEIAUgFIAPgCQAFAAABACQACADAAAHIgBAcIAAAnIAAAkIAAAHQAAABABAAQAAAAAAAAQAAABABAAQAAAAAAAAIAHgEIAKgIIAOgOQAEgEAAgCQAAgCgGgDQgEgDAAgEQAAgHAHgCQAHgDAVAAQAOAAAHADQAGACAAAGQAAAHgKADQgLACgFADQgFADgNAMIgCACIgFAGIgBADQAAADAMARIACACIAZAeQALANAFAEQAEACAKADQAJADAAAGQAAAHgHACQgHADgPAAg");
	this.shape_3.setTransform(5.4,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgsBJQgHgDAAgGQAAgFAHgDIAEgBQADgCACgFQACgFAAgLIgBgKIAAgMIAAgJQAAgagBgJQgBgHgDgDIgHgCQgIgDAAgFQgBgDADgDQADgCAGgDIAUgHIAOgCQAGAAADAUIAAADIAAAAQAIgLAJgHQAHgFAJAAQAKAAAGAFQAHAHgBAKQAAALgEAFQgFAGgJAAIgHgBIgGgFIgEgGQAAgBAAAAQgBgBAAgBQAAAAgBAAQAAgBAAAAQgKAAgFAPQgDAOAAArQAAANABAHQABAGAFACIAFACQAJADAAAGQABAFgJADQgIADgUAAQgWAAgHgDg");
	this.shape_4.setTransform(-8.6,3.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AAgBKQgCgBAAgGIAAgKIAAgBIgBAAQgCAAgDAEIgCACQgHAHgJAEQgIAEgLgBQgLABgKgFQgKgEgGgHQgHgJgDgMQgDgMAAgfIAAgKIAAgLIAAgCQAAgMgBgEQgCgDgFgCIgGgCQgIgCAAgGQAAgDADgCQACgDALgEIAUgFIAQgCQADAAACADQACADAAAHIAAAFIgCA3QAAAdAHAMQAGALAPAAQAQAAAHgOQAHgPAAgkIAAgLQAAgMgBgDQgCgEgFgBIgGgCQgIgCAAgGQAAgDADgCQADgDAKgEIAUgFIAPgCQAFAAABADQACACAAAIIAAAIIgCA7IAAAZIABAKQABAGAIADIAAAAIADABQAIADAAAFQAAADgCADIgJAEIgVAHQgLADgFAAQgEAAgCgDg");
	this.shape_5.setTransform(-23.5,3.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgeBpQgIgDAAgGQgBgGAJgDQAHgDACgCQABgDABgYIABhFIAAgnIgBgYQgBgDgCgCIgJgBIgGAAQgLAAgFACQgGACgEAGIgEAKIgFALIgEAEIgGABQgEABgCgEQgCgEAAgJQAAgTAFgNQAEgLAIAAIABAAQALACASAAIBWAAQASAAAMgCIABAAQAIAAAFALQAEANAAATQAAAJgCAEQgCADgFAAIgEgBIgFgEIgEgLIgFgKQgEgGgGgCQgGgCgKAAIgGAAIgIABQgDACgBADIgBAYIAAAnIAABFQABAYACADQABACAJADQAHADABAGQAAAGgJADQgIADgXAAQgWAAgIgDg");
	this.shape_6.setTransform(-41.7,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.theturkey, new cjs.Rectangle(-53.5,-19.5,107.1,39.1), null);


(lib.thestuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgQAQQgGgHAAgJQAAgJAGgGQAIgHAIAAQAJAAAHAHQAHAGAAAJQAAAJgHAHQgHAHgJAAQgIAAgIgHg");
	this.shape.setTransform(51.8,8.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("Ag2BhQgSgMgBgQQAAgIAFgFQADgEAIAAQAGgBAEAEQAEAEACAGQACALAKAGQAJAHASAAQATgBANgHQANgIAAgLQAAgHgEgDQgGgFgJAAIgRABIgVACQgbAAgOgJQgOgJAAgMQAAgHAFgHQAFgGALgHQgJgIgEgJQgFgJAAgLQABgZARgPQASgRAcABIAPABIAWAEQAGAAAHgDQAGgDAJgGIAFAFIABAFQABAGgFAGQgFAFgJAFIAGAMIABAMQAAAZgSAPQgSAOgcAAIgQgBIgOgCIgEAFIgCAFQAAAIAHACQAHAEAPAAIAVgBIAXgDQAVAAALAJQALAIAAAQQAAAYgYAPQgXAQgiAAQgcAAgTgLgAgXhIQgIAJAAAPQAAAPAIAJQAHAJAMAAQAMAAAHgJQAJgKAAgOQAAgPgIgJQgIgKgMAAQgLAAgIAKg");
	this.shape_1.setTransform(40.5,5.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhHBJQgIgDAAgGQAAgFAHgDIAEgBQAEgCACgFQABgFAAgLIAAgKIAAgMIAAgOQAAgXgBgIQgBgHgEgCIgGgCQgJgDAAgFQAAgDADgDQACgCAGgDIAVgHIAQgCQAEAAACACQACADAAAEIAAAKIAAABIABABIABgBIAAAAIAEgDIADgDQAQgPASABQAKgBAKAFQAKAEAHAJQAGAHADAMQADALAAAYIAAATIAAAJIAAAJQAAAKABAFQACAEAEACIADABQAIADgBAFQAAAGgGADQgHACgXAAQgUAAgIgCQgGgDgBgFQAAgGAIgDIAGgCQADgCABgGIABgWQABgvgGgMQgGgLgQAAQgHAAgHAEQgHAGgEAHQgDAGgCAMIAAAoIAAATQACAEADACIAFACQAIADAAAGQAAAFgIADQgGADgUAAQgXAAgGgDg");
	this.shape_2.setTransform(23.4,3.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgZBpQgIgCAAgHQAAgFAHgCIAEgCQAEgCACgFQABgFAAgLIAAgKIAAgMIAAgPQAAgXgBgGQgBgIgDgBIgHgDQgJgDAAgEQAAgEADgCQACgDAHgDIAWgHIAPgCQAEAAACACQABADAAAHIAAAJIAAAGIgBAlIAAABIgBAkIABAUQACAGADACIAGACQAHADAAAFQAAAGgHACQgHADgUAAQgVAAgHgDgAgRhKQgHgFAAgHQAAgJAHgGQAHgGAKAAQAJAAAGAGQAGAFAAAIQAAAIgGAGQgHAGgKAAQgJAAgGgGg");
	this.shape_3.setTransform(10.4,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgpBqQgHgCAAgHQAAgEAHgCIAEgDQADgBABgFQACgEAAgNIAAgPIAAhGIgRAAQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQgBgBAAgEIAAgEQAAgDABgCQABgBAEgBIAPAAIgBgLIAAgKQAAgXANgMQANgNAYAAQAQAAALAHQALAIAAAMQgBAHgDAEQgEADgHAAQgFAAgEgCQgEgDgCgDIgDgFQgFgLgIAAQgGAAgDAEQgDADAAAGIADARQADAMAAAKIAVAAQAEABABABIABAFIAAAEIgBAFQgBACgEAAIgVAAIAABLQAAATABAGQABAFAEACIAFACQAJADAAAGQAAAFgIADQgHACgUAAQgWAAgHgCg");
	this.shape_4.setTransform(3.4,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgpBqQgHgCAAgHQAAgEAHgCIAEgDQADgBABgFQACgEAAgNIAAgPIAAhGIgQAAQgBAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAgBQgCgBABgEIAAgEQgBgDACgCQACgBADgBIAPAAIgBgLIgBgKQAAgXAOgMQAOgNAXAAQARAAAKAHQALAIgBAMQAAAHgDAEQgEADgHAAQgFAAgEgCQgEgDgCgDIgDgFQgFgLgIAAQgGAAgDAEQgDADAAAGIADARQADAMAAAKIAWAAQADABABABIABAFIAAAEIgBAFQgBACgDAAIgWAAIAABLQAAATABAGQACAFADACIAGACQAIADAAAGQAAAFgHADQgHACgVAAQgWAAgHgCg");
	this.shape_5.setTransform(-5,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AAgBKQgCgBAAgGIAAgKIAAgBIgBAAQgCAAgDAEIgCACQgHAHgJAEQgIAEgLgBQgLABgKgFQgKgEgGgHQgHgJgDgMQgDgMAAgfIAAgKIAAgLIAAgCQAAgMgBgEQgCgDgFgCIgGgCQgIgCAAgGQAAgDADgCQACgDALgEIAUgFIAQgCQADAAACADQACADAAAHIAAAFIgCA3QAAAdAHAMQAGALAPAAQAQAAAHgOQAHgPAAgkIAAgLQAAgMgBgDQgCgEgFgBIgGgCQgIgCAAgGQAAgDADgCQADgDAKgEIAUgFIAPgCQAFAAABADQACACAAAIIAAAIIgCA7IAAAZIABAKQABAGAIADIAAAAIADABQAIADAAAFQAAADgCADIgJAEIgVAHQgLADgFAAQgEAAgCgDg");
	this.shape_6.setTransform(-19.3,3.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgHBZQgIgDgFgEQgFgGgCgIQgCgHAAgXIAAhOIgOAAIgEgBIgBgEIAAgEQAAgEAPgOIAGgEIAGgGQAPgNAGAAIADACQABAAAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAbIAhAAQAEABABABIABAFIAAAEIgBAFQgCACgDAAIgeAAIgDABIAAAEIAABIQAAATADAFQADAFAJAAQAEAAAIgCIAKgDQADAAACACQACACAAADQAAAIgMAHQgNAIgQAAQgIAAgHgCg");
	this.shape_7.setTransform(-33.1,2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgjBrQgRgFgKgGQgHgDgDgMQgEgNAAgRQAAgGACgEQADgDAFAAQAHgBAHANIADAHQAKARALAHQALAHAPAAQAQAAALgKQALgJAAgOQAAgUgrgUIgFgCQgjgOgMgOQgLgMAAgWQAAgaATgRQATgRAgAAIAQACIAVAEIAFgDIAFgCQAEAAADADQADACADAFQAFAJADAKQADAKAAAHQAAAFgDADQgCADgEAAQgIgBgHgKIgCgDQgJgLgJgFQgLgGgMAAQgQABgJAHQgKAIAAANQABAMAHAIQAJAIAeAOIAGACQAbALALAKQAJAIAEAJQAEAKAAAMQAAAfgVAQQgVARglAAQgRAAgQgDg");
	this.shape_8.setTransform(-47,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thestuffing, new cjs.Rectangle(-57.8,-19.5,115.7,39.1), null);


(lib.thesides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgQAQQgGgHAAgJQAAgJAGgGQAIgHAIAAQAJAAAHAHQAHAGAAAJQAAAJgHAHQgHAHgJAAQgIAAgIgHg");
	this.shape.setTransform(35.8,8.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgKBNIgQgDIgEADIgFAAIgDAAIgDgCQgFgEgEgMQgEgMAAgLQgBgEADgDQADgEAEAAQAGAAAHAMIAFAJQAFAGAHADQAJAEAHgBQAKAAAGgEQAFgGAAgIQAAgMgXgMIgJgEQgXgLgIgJQgJgJAAgPQAAgTAOgMQAOgMAVAAIAKAAIAKACIAHgDIAEgBQAHABAHALQAIAMAAAMQgBAGgCADQgCACgEAAQgEAAgDgCQgEgDgEgHQgGgJgFgDQgGgFgJAAQgHAAgFAGQgGAEAAAIQABAHAFAFQAFAFARAJIADABQApAUgBAXQABAVgRAOQgPANgYAAg");
	this.shape_1.setTransform(25.3,3.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgvA3QgWgVAAggQAAghAXgXQAVgWAhAAQAcAAARAQQARARAAAbQAAAJgEADQgCADgLAAIg4AAQgFAAgCgCQgDgDAAgEQAAgEADgCQACgCAFAAIAeAAIAIgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgPgJgJQgKgKgNAAQgRAAgJAPQgJAQAAAVQAAAWANARQALARASAAQALAAAHgCQAIgDAHgFIAFgEQAIgGAEAAQADAAACACQACACABADQgBAEgEAFQgDAFgGAFQgNALgMAEQgMAFgOAAQgeAAgVgWg");
	this.shape_2.setTransform(11.2,3.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AhABZQgRgUAAggQAAgkAUgVQAUgXAfAAIAKABQAFACACADQACADAAAEQAAAIgJAAIgEgBIgEAAQgQAAgKAOQgKAMAAAXQAAAZALAQQALAPAQAAQAPAAAJgIQAIgJAAgQIAAgpIAAhDQAAgKgCgEQgCgEgFgCIgEgBQgJgDAAgFQAAgEADgDQAEgDALgEIAQgFIAOgBQAFAAACADQADACAAAHIgBAHIgBBbIABA9QABAPACABIAKAEQAIACAAAFQAAAHgVAGIgPAEIgLACQgEAAgCgDQgCgCAAgFIAAgHIAAgDIgBgBIgFADIgGAFQgJAHgHADQgJADgJAAQgcAAgRgUg");
	this.shape_3.setTransform(-4.8,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgZBpQgIgCAAgHQAAgFAHgCIAEgCQAEgCACgFQABgFAAgLIAAgKIAAgMIAAgPQAAgXgBgGQgBgIgDgBIgHgDQgJgDAAgEQAAgEADgCQACgDAHgDIAWgHIAPgCQAEAAACACQABADAAAHIAAAJIAAAGIgBAlIAAABIgBAkIABAUQACAGADACIAGACQAHADAAAFQAAAGgHACQgHADgUAAQgVAAgHgDgAgRhKQgHgFAAgHQAAgJAHgGQAHgGAKAAQAJAAAGAGQAGAFAAAIQAAAIgGAGQgHAGgKAAQgJAAgGgGg");
	this.shape_4.setTransform(-18.3,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgkBrQgQgFgLgGQgGgDgDgMQgEgNAAgRQAAgGACgEQADgDAFAAQAHgBAHANIADAHQAKARALAHQAMAHAOAAQAQAAALgKQALgJAAgOQAAgUgrgUIgFgCQgjgOgMgOQgMgMABgWQAAgaATgRQAUgRAeAAIARACIAVAEIAFgDIAGgCQADAAADADQADACADAFQAFAJADAKQADAKAAAHQAAAFgDADQgCADgEAAQgIgBgHgKIgDgDQgIgLgKgFQgJgGgNAAQgQABgJAHQgKAIAAANQAAAMAJAIQAHAIAfAOIAGACQAbALALAKQAJAIAEAJQAEAKAAAMQAAAfgVAQQgVARglAAQgRAAgRgDg");
	this.shape_5.setTransform(-31,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thesides, new cjs.Rectangle(-41.8,-19.5,83.7,39.1), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.leaderboardsignup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAWAtIgWhHIgVBHIgNAAIgbhZIAOAAIAUBHIAWhHIAMAAIAVBHIAVhHIANAAIgbBZg");
	this.shape.setTransform(14.2,4.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgJAvIgJgDQgJgEgGgGQgHgHgDgIQgEgJAAgKQAAgKAEgJQADgIAHgGQAGgHAJgDIAJgDIAJgBQAKAAAJAEIAIAEIAHAGQAHAGADAIQAEAJAAAKQAAAKgEAJQgDAIgHAHIgHAFIgIAFQgJADgKABIgJgBgAgNggQgHACgEAFQgEAFgDAHQgCAHAAAGQAAAHACAHQADAGAEAFQAFAGAGACQAGADAHAAQAIAAAGgDQAGgCAFgGQAEgFADgGQACgHAAgHQAAgGgCgHQgDgHgEgFQgFgFgGgCQgGgDgIAAQgHAAgGADg");
	this.shape_1.setTransform(2.1,4.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAWAtIguhJIgBAAIAABJIgMAAIAAhZIAQAAIAuBHIABAAIAAhHIAMAAIAABZg");
	this.shape_2.setTransform(-8.6,4.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AARAtIgWgoIgOAAIAAAoIgMAAIAAhZIAdAAQAFAAAGABIAKAEQAFADACAFQADAFAAAHQAAAKgGAGQgDADgEABIgJADIAZApgAgTgFIAPAAIAHAAIAHgDIAEgEQACgDAAgEQAAgEgCgDQgBgDgDgBIgGgDIgHAAIgQAAg");
	this.shape_3.setTransform(-20.9,4.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgdAtIAAhZIA5AAIAAALIgtAAIAAAbIArAAIAAAKIgrAAIAAAeIAvAAIAAALg");
	this.shape_4.setTransform(-29.2,4.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgnAtIAAhZIAfAAQAIAAAIACQAJADAHAFQAHAGAEAIIAEAKQABAFAAAFQAAAGgBAFIgEAJIgEAIIgHAGQgHAGgJADQgKACgGAAgAgbAiIAQAAQAIAAAHgCQAGgCAFgFQAGgEACgHIACgGIABgIIgBgHIgCgHQgCgGgGgEQgFgFgGgCQgHgCgIAAIgQAAg");
	this.shape_5.setTransform(-38.2,4.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AARAtIgWgoIgOAAIAAAoIgMAAIAAhZIAdAAQAFAAAGABIAKAEQAFADACAFQADAFAAAHQAAAKgGAGQgDADgEABIgJADIAZApgAgTgFIAPAAIAHAAIAHgDIAEgEQACgDAAgEQAAgEgCgDQgBgDgDgBIgGgDIgHAAIgQAAg");
	this.shape_6.setTransform(-47.2,4.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgJAvIgJgDQgJgEgGgGQgHgHgDgIQgEgJAAgKQAAgKAEgJQADgIAHgGQAGgHAJgDIAJgDIAJgBQAKAAAJAEIAIAEIAHAGQAHAGADAIQAEAJAAAKQAAAKgEAJQgDAIgHAHIgHAFIgIAFQgJADgKABIgJgBgAgNggQgHACgEAFQgEAFgDAHQgCAHAAAGQAAAHACAHQADAGAEAFQAFAGAGACQAGADAHAAQAIAAAGgDQAGgCAFgGQAEgFADgGQACgHAAgHQAAgGgCgHQgDgHgEgFQgFgFgGgCQgGgDgIAAQgHAAgGADg");
	this.shape_7.setTransform(-57.3,4.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.leaderboardsignup, new cjs.Rectangle(-64.4,-5.3,86.8,18.7), null);


(lib.leaderboardpotatoes_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.leaderboardpotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-57.5,-27);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.leaderboardpotatoes_1, new cjs.Rectangle(-57.5,-27,115,54), null);


(lib.leaderboardlogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(64.1,29.1,0.491,0.491);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgUgDgIgEQgJgFAAgNQAAgKAGgHQAFgHAJAAIARAAQAKAAAFgLQADgKgBgXIAAl5QABgXgDgKQgFgLgKAAIgRAAQgJAAgFgHQgGgHAAgKQAAgNAJgFQAIgEAUgDQBegNBrAAQBNAAA1ASQA1ASAnAoQAlAlAVA5QATA4AABEQAABNgZA9QgZA+gwAlQglAegvAOQgxAOhEAAQhrAAhegNgAgvjrQgcAFgKALQgKAMAAAhIAAFjQAAAhAVALQANAHAnADQBNAEAshAQAqg/ABhwQAAhwgrg/Qgrg/hKAAIgdADg");
	this.shape_1.setTransform(30.6,14.8,0.491,0.491);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(39.9,43.4,0.491,0.491);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(25.7,43.4,0.491,0.491);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(11.1,43.4,0.491,0.491);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAvBeIghgxQgFgJgKAAIgtAAQgEAAgDADQgDACgBAFIABAwQAAAHgKACIgPAAQgNAAAAgLIAAi6QAAgIAJAAIBrAAQAgAAAUASQAVAUgBAgQAAAXgOAPQgIAJgPAJQgHAIAEAFIAiAyQAFAHgFAFQgEAEgPAAQgRAAgFgJgAg5g4IAAAuQABAFAEADQAEACAFAAIA+AAQAQAAALgHQALgKAAgPQAAgRgLgJQgLgJgQAAIg+AAQgOAAAAALg");
	this.shape_5.setTransform(-5.5,43.4,0.491,0.491);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAgBABAAQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-21.8,43.4,0.491,0.491);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBlQgFgDAAgFIgOhrQgCgHgFAAQgDAAgDAEIgxA+QgEAFgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBpQgCAKgTAAQgGAAgFgCQgGgDAAgGIAVixQACgJADgCQAEgFALAAQAKAAAFAIIA4BPQAFAIAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAJIAVC1QABAKgXAAQgFAAgFgCg");
	this.shape_7.setTransform(-38.4,43.4,0.491,0.491);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(7.2,-26.7,0.491,0.491);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDxQhFg2gYheIgBgDQgCgLgHABQgGgBgCALIgBABQgYBghGA2QhIA2hoAAQh+AAhMhQQhMhRAAiFQAAiGBMhRQBLhQCAAAQBpAABHA2QBHA3AXBgQACALAGgBQAHAAACgLIABAAQAXhgBGg2QBHg2BoAAQB/AABNBPQBMBQAACGQAACHhMBRQhNBQiBAAQhmAAhHg2gACniqQgpA/AABtQAABtApA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/gAmFiqQgoA/AABtQAABtAoA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/g");
	this.shape_9.setTransform(-10.3,14.9,0.491,0.491);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-48.4,14.8,0.491,0.491);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIQAKgHAIAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(54.1,14.9,0.491,0.491);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAIQgNAIgQABQgTgBgKgIQgLgKgJgYIimm+QgKgZgHgIQgHgHgUgFQgOgBgFgGQgFgFAAgKQAAgXAdAAICvAAQAcAAAAAXQAAAMgHAEQgHAFgRABQgOACgGAEQgGAFAAALQAAAIADALIBzFGQACAFAFAAQAEgBACgFIA/i1QAIgZgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgEgGgEQgFgGAAgJQAAgaAdAAICnAAQAdAAAAAXQAAATgcAFQgRABgFAFQgGAFAAALQAAALAIAZIBfEsQACAFAEAAQAFgBABgFIBdk6QAEgLAAgJQAAgTgdgDQgbgCAAgWQAAgMAHgGQAIgGARAAIElAAQAVAAAIAGQAIAFAAAOQAAAKgGAHQgGAHgJAAIgQAAQgLAAgFAKQgCAJAAAZIAABuQAAAdAFAHQAGAGAXAAIB0AAQAXAAAHgHQADgEAAgGIABgfIAAhoQAAgbgDgHQgFgKgKAAIgQAAQgKAAgHgHQgGgHAAgKQAAgOAIgFQAJgGAWAAICaAAQAWAAAJAGQAJAFAAAOQAAAKgHAHQgGAHgJAAIgSAAQgEAAgEADQgFAEgBADQgDAKAAAYIAAF8QAAAYADALQABADAFAEQAEACAEAAIASAAQAJAAAGAIQAHAGAAAKQAAAOgJAGQgIAEgXAAIiaAAQgWAAgIgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIAQAAQAKABAFgKQADgIAAgbIAAh8IgBgdQAAgHgDgDQgHgIgXAAIh0AAQgXAAgGAHQgFAGAAAeIAACAQAAAZACAKQAFAKALgBIAQAAQAJAAAGAIQAGAGAAALQAAANgIAGQgIAEgVAAIiaAAQgWAAgJgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIARAAQAEAAAFgCQAEgEABgDQADgIAAgbIAAl8QAAgwgkAEQgLABgHAJQgIAKgGAVIiHGzQgJAfgKAMQgLAKgTABQgTAAgLgKg");
	this.shape_12.setTransform(-36.7,-18.1,0.491,0.491);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDACgEQADgIAAgXIAAmAQAAgZgDgHQgDgMgLAAIgRAAQgKABgGgHQgHgHAAgKQAAgOAJgFQAJgGAWAAICcAAQAWAAAJAGQAJAFAAAOQAAAKgGAHQgHAHgJgBIgSAAQgOAAgDAMQgDAFAAAbIAAFkQAAAdACAJQACAJAIAFQAGAFALABQALACAaAAIAwAAQAvAAAPggIAIgQQAIgPAPAAQAMgBAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(34,-18.3,0.491,0.491);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgaAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(56.2,-18.3,0.491,0.491);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKg");
	this.shape_15.setTransform(0,0,0.491,0.491);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.leaderboardlogo, new cjs.Rectangle(-86,-86,172,172), null);


(lib.leaderboardctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63A01").s().p("Ar0CoIAAlPIXpAAIAAFPg");
	this.shape.setTransform(-19.4,3.8,0.842,0.971);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.leaderboardctarectangle, new cjs.Rectangle(-83.1,-12.5,127.6,32.6), null);


(lib.holidaymainsorange = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.leaderboardorange();
	this.instance.parent = this;
	this.instance.setTransform(-58.5,-25);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsorange, new cjs.Rectangle(-58.5,-25,117,50), null);


(lib.holidaymainscranberries = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.leaderboardcranberries();
	this.instance.parent = this;
	this.instance.setTransform(-41,-20.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscranberries, new cjs.Rectangle(-41,-20.5,82,41), null);


(lib.holidaymainscinnamonbuns = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.leaderboardcinnamonbuns();
	this.instance.parent = this;
	this.instance.setTransform(-96.5,-45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscinnamonbuns, new cjs.Rectangle(-96.5,-45,193,90), null);


(lib.holidaymainsbrusselsprouts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.leaderboardbrusselsprouts();
	this.instance.parent = this;
	this.instance.setTransform(-65.5,-43);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsbrusselsprouts, new cjs.Rectangle(-65.5,-43,131,86), null);


(lib.holidaymainsbottomcorner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.leaderboardstuffinguse();
	this.instance.parent = this;
	this.instance.setTransform(-35.5,-30);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsbottomcorner, new cjs.Rectangle(-35.5,-30,71,60), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("Eg3igGjMBvFAAAIAANHMhvFAAAg");
	this.shape.setTransform(0,0,1.023,1.06);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-364.5,-45.5,729,91), null);


(lib.desserts = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgPAQQgHgHAAgJQAAgJAHgGQAGgHAJAAQAKAAAGAHQAHAGAAAJQAAAJgHAHQgGAHgKAAQgJAAgGgHg");
	this.shape.setTransform(57.1,8.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgKBNIgQgDIgEADIgFAAIgDAAIgDgCQgFgEgEgMQgEgMAAgLQAAgEACgDQADgEADAAQAHAAAHAMIAFAJQAFAGAHADQAIAEAIgBQAKAAAFgEQAGgGAAgIQAAgMgXgMIgJgEQgXgLgIgJQgJgJABgPQAAgTANgMQAOgMAVAAIAJAAIALACIAHgDIAFgBQAHABAGALQAIAMAAAMQgBAGgCADQgDACgDAAQgEAAgDgCQgEgDgEgHQgGgJgGgDQgFgFgJAAQgHAAgFAGQgFAEgBAIQAAAHAGAFQAFAFASAJIACABQAoAUAAAXQAAAVgPAOQgQANgYAAg");
	this.shape_1.setTransform(46.5,3.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgHBZQgIgDgFgEQgFgGgCgIQgCgHAAgXIAAhOIgOAAIgEgBIgBgEIAAgEQAAgEAPgOIAGgEIAGgGQAPgNAGAAIADACQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIAAAbIAhAAQAEABABABIABAFIAAAEIgBAFQgCACgDAAIgeAAIgDABIAAAEIAABIQAAATADAFQADAFAJAAQAEAAAIgCIAKgDQADAAACACQACACAAADQAAAIgMAHQgNAIgQAAQgIAAgHgCg");
	this.shape_2.setTransform(35.1,2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgsBJQgHgDAAgGQAAgFAHgDIAEgBQADgCACgFQACgFAAgLIAAgKIAAgMIAAgJQAAgagBgJQgCgHgDgDIgHgCQgJgDABgFQAAgDACgDQADgCAHgDIATgHIAOgCQAGAAADAUIAAADIABAAQAHgLAJgHQAHgFAJAAQAKAAAGAFQAHAHAAAKQAAALgGAFQgEAGgIAAIgIgBIgGgFIgEgGQAAgBAAAAQgBgBAAgBQAAAAgBAAQAAgBAAAAQgLAAgEAPQgDAOAAArQAAANABAHQABAGAEACIAGACQAKADgBAGQAAAFgIADQgIADgUAAQgWAAgHgDg");
	this.shape_3.setTransform(24.5,3.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgvA3QgWgVAAggQAAghAXgXQAVgWAhAAQAcAAARAQQARARAAAbQAAAJgEADQgCADgLAAIg4AAQgFAAgCgCQgDgDAAgEQAAgEADgCQACgCAFAAIAeAAIAIgBQAAAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAAAQAAgPgJgJQgKgKgNAAQgRAAgJAPQgJAQAAAVQAAAWANARQALARASAAQALAAAHgCQAIgDAHgFIAFgEQAIgGAEAAQADAAACACQACACABADQgBAEgEAFQgDAFgGAFQgNALgMAEQgMAFgOAAQgeAAgVgWg");
	this.shape_4.setTransform(10.8,3.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgLBNIgPgDIgFADIgEAAIgDAAIgDgCQgFgEgEgMQgFgMAAgLQAAgEADgDQACgEAEAAQAHAAAHAMIAGAJQAEAGAIADQAHAEAIgBQAKAAAFgEQAGgGAAgIQAAgMgYgMIgIgEQgXgLgIgJQgIgJgBgPQAAgTAOgMQANgMAWAAIAKAAIAKACIAHgDIAEgBQAIABAHALQAGAMAAAMQAAAGgCADQgDACgEAAQgDAAgDgCQgDgDgFgHQgFgJgHgDQgFgFgIAAQgIAAgGAGQgEAEAAAIQgBAHAGAFQAFAFARAJIACABQApAUABAXQgBAVgQAOQgPANgYAAg");
	this.shape_5.setTransform(-3.5,3.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgKBNIgQgDIgFADIgEAAIgDAAIgDgCQgFgEgEgMQgFgMABgLQgBgEADgDQACgEAFAAQAGAAAHAMIAGAJQAEAGAHADQAJAEAHgBQAKAAAGgEQAFgGAAgIQAAgMgXgMIgJgEQgXgLgIgJQgJgJAAgPQAAgTAOgMQAOgMAVAAIAKAAIAKACIAHgDIAEgBQAHABAIALQAGAMABAMQAAAGgDADQgCACgEAAQgEAAgDgCQgEgDgEgHQgGgJgFgDQgGgFgJAAQgHAAgFAGQgGAEAAAIQABAHAFAFQAFAFARAJIADABQApAUgBAXQABAVgRAOQgPANgYAAg");
	this.shape_6.setTransform(-16.2,3.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgwA3QgUgVgBggQAAghAXgXQAVgWAhAAQAcAAARAQQARARAAAbQgBAJgDADQgCADgLAAIg4AAQgFAAgCgCQgDgDAAgEQAAgEADgCQACgCAFAAIAeAAIAIgBQAAAAAAgBQABAAAAgBQAAAAAAgBQABgBAAAAQAAgPgKgJQgKgKgNAAQgSAAgIAPQgJAQAAAVQAAAWANARQALARASAAQALAAAHgCQAIgDAHgFIAFgEQAIgGAEAAQADAAACACQACACAAADQAAAEgEAFQgDAFgGAFQgNALgMAEQgMAFgOAAQgfAAgVgWg");
	this.shape_7.setTransform(-30.3,3.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgfBqIgTAAIgMAAIgMAAQgSAAgGgCQgGgCAAgHQABgFAHgDQAIgDABgDQACgDACgWIABg4IgBg3QgCgWgCgDQgBgCgIgDQgHgEgBgFQABgGAFgDQAHgCASAAIAMAAIAQAAIATAAIARgBQA2AAAeAdQAeAcAAA0QAAAzgfAaQgfAbg6AAgAgghTQgGACgCAFQgCAFgBARIgBAtIABA4QABAXACAFQABAEALADQAJAEANAAQAiAAARgVQAQgUABgqQAAgqgUgXQgTgYgkAAQgMAAgHADg");
	this.shape_8.setTransform(-49.5,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.desserts, new cjs.Rectangle(-63,-19.5,126.2,39.1), null);


(lib.ctarollovervideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AuQCqIAAlTIchAAIAAFTg");
	this.shape.setTransform(-19.1,3.6,0.702,0.987);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarollovervideo, new cjs.Rectangle(-83.1,-13.2,128.1,33.6), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.ctarollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(2));

	// Layer 1
	this.instance = new lib.ctarollovervideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-83.1,-13.2,128.1,33.6);


// stage content:
(lib.leaderboardholidaymains = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_57 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_253 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(57).call(this.frame_57).wait(196).call(this.frame_253).wait(4));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(365.8,47.1,3.544,0.143,0,0,0,0.3,0.7);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(257));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(257));

	// logo
	this.instance_1 = new lib.leaderboardlogo();
	this.instance_1.parent = this;
	this.instance_1.setTransform(660.8,44.7,0.667,0.667,0,0,0,0.1,0.2);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({regX:0,regY:0,scaleX:0.02,scaleY:0.02,x:660.9},0).to({regX:0.1,regY:0.2,scaleX:0.74,scaleY:0.74,x:660.8,alpha:1},6).to({scaleX:0.67,scaleY:0.67},7).wait(235));

	// fade-from-black
	this.instance_2 = new lib.blackwideskyscraper();
	this.instance_2.parent = this;
	this.instance_2.setTransform(366.7,50.5,4.456,0.171,0,0,0,0.6,0.6);
	this.instance_2.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_2.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({regX:0.2,regY:0.7,scaleY:0.16,x:364.9,y:47,alpha:0},9).wait(248));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("EglrAKeIAA07MBOXAAAIAAU7g");
	mask.setTransform(260.4,54.2);

	// well-make
	this.instance_3 = new lib.wellmakethe();
	this.instance_3.parent = this;
	this.instance_3.setTransform(126.2,26.5);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(47).to({x:-242.8},0).to({x:136.2,alpha:1},10,cjs.Ease.get(1)).to({x:126.2},8,cjs.Ease.get(1)).wait(154).to({alpha:0},5).wait(33));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("EglrAKeIAA07MBOXAAAIAAU7g");
	mask_1.setTransform(260.4,54.2);

	// the-turkey
	this.instance_4 = new lib.theturkey();
	this.instance_4.parent = this;
	this.instance_4.setTransform(286.5,26.5);
	this.instance_4.alpha = 0;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(47).to({x:-82.4},0).to({x:296.5,alpha:1},10,cjs.Ease.get(1)).to({x:286.5},8,cjs.Ease.get(1)).wait(34).to({alpha:0},5).wait(153));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("EglrAKeIAA07MBOXAAAIAAU7g");
	mask_2.setTransform(260.4,54.2);

	// well-make-the-feast
	this.instance_5 = new lib.wellmakethefeast();
	this.instance_5.parent = this;
	this.instance_5.setTransform(145.9,17.6);
	this.instance_5.alpha = 0;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(229).to({x:-129.1},0).to({x:150.9,alpha:1},10,cjs.Ease.get(1)).to({x:145.9},8,cjs.Ease.get(1)).wait(10));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("EglrAKeIAA07MBOXAAAIAAU7g");
	mask_3.setTransform(260.4,54.2);

	// you-take-the-credit
	this.instance_6 = new lib.youtakethecredit();
	this.instance_6.parent = this;
	this.instance_6.setTransform(90.7,39.5);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(237).to({x:-184.3},0).to({x:95.7,alpha:1},10,cjs.Ease.get(1)).to({x:90.7},8,cjs.Ease.get(1)).wait(2));

	// the-stuffing
	this.instance_7 = new lib.thestuffing();
	this.instance_7.parent = this;
	this.instance_7.setTransform(290.8,26.5);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(99).to({alpha:1},10).wait(30).to({alpha:0},5).wait(113));

	// the-sides
	this.instance_8 = new lib.thesides();
	this.instance_8.parent = this;
	this.instance_8.setTransform(274.8,26.5);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(139).to({alpha:1},10).wait(30).to({alpha:0},5).wait(73));

	// the-desserts
	this.instance_9 = new lib.desserts();
	this.instance_9.parent = this;
	this.instance_9.setTransform(296,26.5);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(179).to({alpha:1},10).wait(30).to({alpha:0},5).wait(33));

	// order-now (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("AuDB4IAAjvIcHAAIAADvg");
	mask_4.setTransform(125.5,64.5);

	// order-now
	this.instance_10 = new lib.leaderboardsignup();
	this.instance_10.parent = this;
	this.instance_10.setTransform(104,63.4);
	this.instance_10.alpha = 0;

	var maskedShapeInstanceList = [this.instance_10];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(57).to({x:-63.2},0).to({x:114,alpha:1},10,cjs.Ease.get(1)).to({x:104},6,cjs.Ease.get(1)).wait(184));

	// cta-rollover-mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("AttG4IAAnBIejAAIAAHBg");
	mask_5.setTransform(107.8,44);

	// cta-rollover
	this.cta_rollover = new lib.ctarollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(103.6,63.9);

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(57).to({x:-63.2},0).to({x:113.6},10,cjs.Ease.get(1)).to({x:103.6},6,cjs.Ease.get(1)).wait(184));

	// cta-mask (mask)
	var mask_6 = new cjs.Shape();
	mask_6._off = true;
	mask_6.graphics.p("AttG4IAAnBIejAAIAAHBg");
	mask_6.setTransform(107.8,44);

	// cta-rectangle
	this.instance_11 = new lib.leaderboardctarectangle();
	this.instance_11.parent = this;
	this.instance_11.setTransform(103.6,63.8);
	this.instance_11.alpha = 0;

	var maskedShapeInstanceList = [this.instance_11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_6;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(57).to({x:-63.2,y:63.3},0).to({x:113.6,y:63.8,alpha:1},10,cjs.Ease.get(1)).to({x:103.6},6,cjs.Ease.get(1)).wait(184));

	// cinnamon-buns
	this.instance_12 = new lib.holidaymainscinnamonbuns();
	this.instance_12.parent = this;
	this.instance_12.setTransform(592.5,45);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(39).to({alpha:1},10).wait(208));

	// brussel-sprouts
	this.instance_13 = new lib.holidaymainsbrusselsprouts();
	this.instance_13.parent = this;
	this.instance_13.setTransform(469.5,47);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(33).to({alpha:1},10).wait(214));

	// orange-slices
	this.instance_14 = new lib.holidaymainsorange();
	this.instance_14.parent = this;
	this.instance_14.setTransform(416.5,25);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(27).to({alpha:1},10).wait(220));

	// cranberries
	this.instance_15 = new lib.holidaymainscranberries();
	this.instance_15.parent = this;
	this.instance_15.setTransform(379,69.5);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(21).to({alpha:1},10).wait(226));

	// potatoes
	this.instance_16 = new lib.leaderboardpotatoes_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(247.5,63);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(15).to({alpha:1},10).wait(232));

	// bowl-orange
	this.instance_17 = new lib.holidaymainsbottomcorner();
	this.instance_17.parent = this;
	this.instance_17.setTransform(35.5,75);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(9).to({alpha:1},10).wait(238));

	// table
	this.instance_18 = new lib.leaderboardholidaymainstable();
	this.instance_18.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(257));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(362.2,32.2,731.8,117.8);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 728,
	height: 90,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_.png?1508793509191", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;